### PR TITLE
Fall 2015 Website Update

### PR DESCRIPTION
**Pull request by ownzandy**
Preliminary update for fall 2015 website

### CODE REVIEW

**Comment by cranberryofdoom** [comment]
@ownzandy great! gonna look at it tonight (:

**Comment by cranberryofdoom** [comment]
Looks good. You were right to change the changing the years, if I recall correctly, the years will work only if you add a new semester in the DB. And then once you associate a mentor under the "fall 2015" semester, it'll show up accordingly.

**Comment by ownzandy** [comment]
That makes sense, so I was wondering how to push the changes to heroku. I know there was discussion about moving the server, but I think we're trying to get it up and running as soon as possible for registration, sponsors, etc. so we'll probably stay on the current server for the time being.

**Comment by cranberryofdoom** [comment]
In regards to the server, the conversation that you're thinking of is actually *specifically* the reg.hackduke.org subdomain. This DNS points to Bojia's servers, in which IF we choose to not use that anymore, we should point that subdomain to whatever (Google Form, Typeform, another rolled out form) that we're going to use. I'd suggest talking to Bojia considering what him and Logan made was fairly good for our uses.

What I explained above has nothing to do with pushing the changes that you made, to Heroku, haha. You'd need to have access to the heroku dyno in order to be able to push changes in master to production. I'll figure out how to give certain people that access in bit.

**Pull request merged**
